### ISSUE TITLE
Getting corrupt error on opening merged word documents.

### ISSUE THREAD

**Issue by abhinovpankaj** [SPFxAppDev/docxmerger#1]
I have tried this library, it is not working as expected. 
and sometimes even the merged document is not even generated.
Attaching the 2 word files which I am trying to merge.

<img width="285" alt="image" src="https://github.com/user-attachments/assets/9ba20b96-15d2-4edf-80a3-ff1fbee6c300">

[673cc1de78702a04ec1b4032_Visual.docx](https://github.com/user-attachments/files/17818653/673cc1de78702a04ec1b4032_Visual.docx)
[projectheader.docx](https://github.com/user-attachments/files/17818686/projectheader.docx)

**Comment by SPFxAppDev** [comment]
Hi @abhinovpankaj,

Thank you for reporting the issue. Unfortunately, I cannot reproduce the problem. I downloaded the files and tried to merge them. The generated file was valid and could be opened with the latest Word version. You can try it yourself here: 
https://codepen.io/SimpleBase/pen/YzgOpvj

This is the generated file:

[output.docx](https://github.com/user-attachments/files/17819501/output.docx)

**Comment by abhinovpankaj** [comment]
` var docx = new DocxMerger({},fileList);
             // const transientPath = path.resolve(`${fileName}_transient.${reportFormat}`);
              const absolutePath = path.resolve(`${fileName}.${reportFormat}`);
              //console.log(transientPath);
              docx.save('nodebuffer', async function (data) {
                  
                  console.log('inside document save');
                  await fsp.writeFile(absolutePath, data);       
                  //recreateFile(transientPath,headerPath,fileName,reportFormat) ;   
              });
              `

This is how I am using to merge the files.

**Comment by SPFxAppDev** [comment]
But the method `save()` has no parameters. It is just `save()`, which returns a `Promise<any>`. The “original” package/repository is different from this package. If you want to specify the type of zip package to return, you need to specify it in the `merge` method, like this:

```typescript
const docx = new DocxMerger();
  await docx.merge(filesToMerge, { jsZipGenerateOptions: {
        type: 'nodebuffer',
        compression: 'DEFLATE',
        compressionOptions: { level: 4 },
      }},);
  const mergedFile = await docx.save();
```

PS: The `merge` methode is also different

**Comment by abhinovpankaj** [comment]
tried this but getting exceptions now.
So, definitely I am doing something wrong.
I am using node.js.

filesToMerge variable is list of file paths? or arraybuffer or binary ( as in the original library)
what is the return type of docx.save, does it return arraybuffer which needs to be written to a file ?

**Comment by SPFxAppDev** [comment]
In the previous examples, `filesToMerge` is an array of buffer arrays or binaries. I would suggest checking my codepen.io example because this works well

**Comment by abhinovpankaj** [comment]
I already checked that but its typescript i am not usre if we have arraybuffer in node. Will give it a try but the output file has missing header and footer images .

**Comment by SPFxAppDev** [comment]
As already mentioned, this example works well with your example: https://codepen.io/SimpleBase/pen/YzgOpvj

**Comment by abhinovpankaj** [comment]
ReferenceError: XMLSerializer is not defined\n    at DocxMerger.<anonymous> (/Users/abhinovpankaj/Development/Projects/deckinspectorfunctionApp/src/node_modules/@spfxappdev/docxmerger/lib/DocxMerger.js:176:25)\n    at step (/Users/abhinovpankaj/Development/Projects/deckinspectorfunctionApp/src/node_modules/@spfxappdev/docxmerger/lib/DocxMerger.js:44:23)\n    at Object.next (/Users/abhinovpankaj/Development/Projects/deckinspectorfunctionApp/src/node_modules/@spfxappdev/docxmerger/lib/DocxMerger.js:25:53)\n    at /Users/abhinovpankaj/Development/Projects/deckinspectorfunctionApp/src/node_modules/@spfxappdev/docxmerger/lib/DocxMerger.js:19:71\n    at new Promise (<anonymous>)\n    at __awaiter (/Users/abhinovpankaj/Development/Projects/deckinspectorfunctionApp/src/node_modules/@spfxappdev/docxmerger/lib/DocxMerger.js:15:12)\n    at DocxMerger.mergeBody (/Users/abhinovpankaj/Development/Projects/deckinspectorfunctionApp/src/node_modules/@spfxappdev/docxmerger/lib/DocxMerger.js:170:16)\n    at D… …
message =
'XMLSerializer is not defined'
stack =
'ReferenceError: XMLSerializer is not defined\n    at DocxMerger.<anonymous> (/Users/abhinovpankaj/Development/Projects/deckinspectorfunctionApp/src/node_modules/@spfxappdev/docxmerger/lib/DocxMerger.js:176:25)\n   

Also, I mentioned, the sample which you gave is **not working as expected the headers and footers are getting removed**. 

Updated code.
`
 ```
const promises = projectDocxList.map(async (filePath) => {
        try {
          const fileBuffer = await fs.readFile(filePath);
          return fileBuffer.buffer; // Convert Buffer to ArrayBuffer
        } catch (err) {
          console.error(`Failed to read file: ${filePath}`, err);
          throw err;
        }
      });
      
      // Wait for all promises to resolve
      const filesToMerge = await Promise.all(promises);

      const docx = new DocxMerger();
      await docx.merge(filesToMerge,{ jsZipGenerateOptions: {
        type: 'nodebuffer',
        compression: 'DEFLATE',
        compressionOptions: { level: 4 },
      }});
      const mergedFile = await docx.save();
```
`

Attched the files which is resulting in corrupt document genration.
[projectheader.docx](https://github.com/user-attachments/files/17826525/projectheader.docx)
[673cc1de78702a04ec1b4032_Visual.docx](https://github.com/user-attachments/files/17826526/673cc1de78702a04ec1b4032_Visual.docx)

**Comment by abhinovpankaj** [comment]
Was waiting for a response here.

**Comment by SPFxAppDev** [comment]
Hello @abhinovpankaj, please excuse the late reply. To be honest, I completely forgot about it. Back to the topic: Just because you are using the NodeJS application does not mean that the other `types` are “not supported.” For example, you can also use `arraybuffer`. 

Just for your information: It is not necessary to use the `Array.map` function with an asynchronous function and an await in combination with the `Promise.all` function. This is because in this case, all your promises have already been resolved. I recommend using the following code:

```typescript
const filesToMerge = [];


for (const filePath of projectDocxList) {
  try {
    const fileBuffer = await fs.readFile(filePath);
    filesToMerge.push(fileBuffer.buffer);
  } catch (err) {
    console.error(`Failed to read file: ${filePath}`, err);
  }
}

const docx = new DocxMerger();
//...Other code
```

Now to the headers and footers topic. You're right about that. The document generated in the first example did not have any headers or footers. But that's due to something else. Since, technically speaking, different headers/footers cannot be merged, only the header/footer from the FIRST document is used. In this case, that means the order is decisive. So if the first document has NO header/footer, ALL documents will have none, even if the second document has one. This is what the result would look like if you merged the first document with header/footer with the other document.

[output (2).docx](https://github.com/user-attachments/files/23500471/output.2.docx)

But now to your error. The actual reason you are getting an error is because it is in a NodeJS environment. I am using the `XMLSerializer` class, which does NOT exist in nodeJS environments; it is a class that only exists in browsers and is attached to the window object. The same applies to `DOMParser`. 

If I want to support both, I would have to adapt the solution. I will look into this soon and try to fix it.
